# `exists` testcase will use file extension from here
source_name: pa1.s

# max number of points for submitting code with the file extension defined above
exists_max: 10

# max number of points for code compiling
compiles_max: 20

# max number of points for passing testcases
test_case_max: 70

# max number of points for having code that is recursive
# overflow testcase must be in `./testcases/big.in` if this field is provided
recursive_max: 10
