#!/usr/bin/env bash

#cp /autograder/submission/pa1.s /autograder/source/pa1.s

cd /autograder/source

cd ./emulator/scripts

NCPU=2
MEM=1G

qemu-system-aarch64 -smp ${NCPU} -m ${MEM} -M virt -cpu cortex-a57  \
                    -initrd ./emulator/initrd.img-4.9.0-4-arm64 \
                    -kernel ./emulator/vmlinuz-4.9.0-4-arm64 -append "root=/dev/sda2 console=ttyAMA0" \
                    -global virtio-blk-device.scsi=off \
                    -device virtio-scsi-device,id=scsi \
                    -drive file=./emulator/disk.qcow2,id=rootimg,cache=unsafe,if=none \
                    -device scsi-hd,drive=rootimg \
                    -device e1000,netdev=net0 \
                    -netdev user,id=net0,hostfwd=tcp::3101-:22 \
                    -nic user,model=virtio-net-pci \
					-daemonize \
					-display none


cd ../../

# to make sure qemu has had a chance to start
sleep 10

python3 grade.py
